#!/usr/bin/env bash
# ce-rootsync-init.sh — turn ~/ce-net into a LOCAL-ONLY git "meta-repo" that tracks the loose
# top-level files (AGENTS.md, CLAUDE.md, notes/, PLAN/, scripts, ...) which ce-gitsync's per-repo
# sync cannot see. ce-gitsync auto-includes the root once ~/ce-net/.git exists, so this is the only
# step needed: the running daemon then syncs your docs/notes device-to-device with full git history.
#
# LOCAL ONLY: this script never adds a remote and never pushes. The meta-repo exists purely to give
# ce-gitsync something to diff. Run the SAME script on every machine (mac + debian) once.
# Idempotent: re-run any time (e.g. after cloning a new sub-repo) to refresh the sub-repo ignore list.
set -euo pipefail

ROOT="${CE_GITSYNC_ROOT:-$HOME/ce-net}"
cd "$ROOT"

# Regenerate .gitignore: junk + secrets + every current sub-repo (each synced on its own by ce-gitsync).
{
  echo "# ~/ce-net meta-repo .gitignore — generated by tools/ce-rootsync-init.sh."
  echo "# Tracks loose top-level docs/notes/scripts; ignores every CE sub-repo (synced separately)."
  echo "# LOCAL ONLY: never 'git remote add' / never push this repo. Re-run the script after adding repos."
  echo
  echo "# --- scratch / build / os ---"
  printf '%s\n' .DS_Store '*.log' '*.tmp' target/ 'target-*/' node_modules/ dist/ build/ out/ \
    .next/ .svelte-kit/ __pycache__/ '*.pyc' .venv/ venv/ .cache/
  echo
  echo "# --- local agent/build state (machine-specific, never sync) ---"
  printf '%s\n' .claude/ .claude_tmp/ .cargo-shared/ .cargo/ .worktrees/ trash/
  echo
  echo "# --- secrets (never sync) ---"
  printf '%s\n' .env '*.env' '*.token' '*.key' '*.pem' '*.secret'
  echo
  echo "# --- CE sub-repos: each is its own git repo, synced independently by ce-gitsync ---"
  # Match sub-repos AND git worktrees: a worktree's .git is a FILE (gitdir pointer), a repo's is a
  # DIR. Use -e so both are ignored (e.g. ce-fabric is a worktree of ce/, synced via the ce repo).
  for d in */; do
    [ -e "${d}.git" ] && echo "/${d}"
  done | sort
} > .gitignore

if [ ! -d .git ]; then
  git init -q
  git -c init.defaultBranch=main symbolic-ref HEAD refs/heads/main 2>/dev/null || true
  echo "initialized local meta-repo at $ROOT"
else
  echo "meta-repo already present at $ROOT (refreshed .gitignore)"
fi

git add -A
if ! git diff --cached --quiet; then
  git -c user.name=ce-gitsync -c user.email=gitsync@ce-net \
      commit -q -m "rootsync: $(uname -n | cut -d. -f1) $(date '+%Y-%m-%d %H:%M:%S')"
  echo "committed loose top-level files"
else
  echo "nothing new to commit"
fi

echo "--- tracked loose entries (top level) ---"
git ls-files | cut -d/ -f1 | sort -u | sed 's/^/  /'
echo "ce-gitsync (empty allowlist) will now sync this root automatically."
